### ISSUE TITLE
Use stylized checkbox in facets after known Materialize bug is fixed

### ISSUE THREAD

**Issue by chadokruse** [chadokruse/algolia-materialize-jekyll#7]
Currently the stylized checkbox is hidden due to [this Materialize bug](https://github.com/Dogfalo/materialize/issues/5062).

Indications are a fix will come with Materialize 1.0 release.

Reproduction:
https://codepen.io/anon/pen/GMBzjX

**Comment by bettyorganero** [comment]
Hello,
We need a personal appID, apiKey and indexName? if yes where I can do it? Thanks

**Comment by chadokruse** [comment]
@bettyorganero Yes, you need to sign up for an account at [Algolia](http://goto.algolia.com/l/139121/2017-10-24/26gc84). Those three items are your Algolia credentials. 

Relevant docs: https://community.algolia.com/instantsearch.js/v2/getting-started.html#initialization

Also - a request: you posted your question under an existing issue that is unrelated. Happy to answer questions and help where I can, but it's helpful if you open up a [New Issue](https://github.com/chadokruse/algolia-materialize-jekyll/issues/new) as it helps me keep the project organized. Thanks!

**Comment by bettyorganero** [comment]
Ok thank you for answer. Sorry for the mistake in the future I will follow your recommendations.
